// lib/astrologer/utils/countryCode.ts
// Centralized country name to ISO code resolver

const countryCodeMap: Record<string, string> = {
  'Türkiye': 'TR',
  'Turkey': 'TR',
  'United States': 'US',
  'USA': 'US',
  'United Kingdom': 'GB',
  'UK': 'GB',
  'Germany': 'DE',
  'Deutschland': 'DE',
  'France': 'FR',
  'Spain': 'ES',
  'España': 'ES',
  'Italy': 'IT',
  'Italia': 'IT',
  'Canada': 'CA',
  'Australia': 'AU',
  'Avustralya': 'AU',
  'Japan': 'JP',
  'China': 'CN',
  'India': 'IN',
  'Brazil': 'BR',
  'Brasil': 'BR',
  'Russia': 'RU',
  'Россия': 'RU',
  'Netherlands': 'NL',
  'Nederland': 'NL',
  'Belgium': 'BE',
  'België': 'BE',
  'Switzerland': 'CH',
  'Suisse': 'CH',
  'Schweiz': 'CH',
  'Austria': 'AT',
  'Österreich': 'AT',
  'Sweden': 'SE',
  'Sverige': 'SE',
  'Norway': 'NO',
  'Norge': 'NO',
  'Denmark': 'DK',
  'Danmark': 'DK',
  'Finland': 'FI',
  'Suomi': 'FI',
  'Poland': 'PL',
  'Polska': 'PL',
  'Czech Republic': 'CZ',
  'Česko': 'CZ',
  'Czechia': 'CZ',
  'Hungary': 'HU',
  'Magyarország': 'HU',
  'Greece': 'GR',
  'Ελλάδα': 'GR',
  'Portugal': 'PT',
  'Ireland': 'IE',
  'Éire': 'IE',
  'New Zealand': 'NZ',
  'South Korea': 'KR',
  '한국': 'KR',
  'South Africa': 'ZA',
  'Mexico': 'MX',
  'México': 'MX',
  'Argentina': 'AR',
  'Chile': 'CL',
  'Colombia': 'CO',
  'Peru': 'PE',
  'Venezuela': 'VE',
  'Uruguay': 'UY',
  'Ecuador': 'EC',
  'Bolivia': 'BO',
  'Paraguay': 'PY',
  'Guyana': 'GY',
  'Suriname': 'SR',
  'French Guiana': 'GF',
  'Israel': 'IL',
  'ישראל': 'IL',
  'Palestine': 'PS',
  'Egypt': 'EG',
  'مصر': 'EG',
  'Morocco': 'MA',
  'المغرب': 'MA',
  'Algeria': 'DZ',
  'الجزائر': 'DZ',
  'Tunisia': 'TN',
  'تونس': 'TN',
  'Libya': 'LY',
  'ليبيا': 'LY',
  'Sudan': 'SD',
  'السودان': 'SD',
  'Ethiopia': 'ET',
  'ኢትዮጵያ': 'ET',
  'Kenya': 'KE',
  'Uganda': 'UG',
  'Tanzania': 'TZ',
  'Rwanda': 'RW',
  'Burundi': 'BI',
  'Democratic Republic of the Congo': 'CD',
  'République démocratique du Congo': 'CD',
  'Republic of the Congo': 'CG',
  'République du Congo': 'CG',
  'Gabon': 'GA',
  'Cameroon': 'CM',
  'Cameroun': 'CM',
  'Central African Republic': 'CF',
  'République centrafricaine': 'CF',
  'Chad': 'TD',
  'تشار': 'TD',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'Ghana': 'GH',
  'Ivory Coast': 'CI',
  "Côte d'Ivoire": 'CI',
  'Mali': 'ML',
  'Burkina Faso': 'BF',
  'Senegal': 'SN',
  'Gambia': 'GM',
  'Guinea': 'GN',
  'Guinée': 'GN',
  'Sierra Leone': 'SL',
  'Liberia': 'LR',
  'Guinea-Bissau': 'GW',
  'Guiné-Bissau': 'GW',
  'Mauritania': 'MR',
  'موريتانيا': 'MR',
  'Western Sahara': 'EH',
  'الصحراء الغربية': 'EH',
  'Angola': 'AO',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
  'Botswana': 'BW',
  'Namibia': 'NA',
  'Lesotho': 'LS',
  'Swaziland': 'SZ',
  'Eswatini': 'SZ',
  'Madagascar': 'MG',
  'Madagasikara': 'MG',
  'Mauritius': 'MU',
  'Moris': 'MU',
  'Seychelles': 'SC',
  'Sesel': 'SC',
  'Comoros': 'KM',
  'Komori': 'KM',
  'Maldives': 'MV',
  'ދިވެހިރާއްޖެ': 'MV',
  'Sri Lanka': 'LK',
  'ශ්‍රී ලංකාව': 'LK',
  'Bangladesh': 'BD',
  'বাংলাদেশ': 'BD',
  'Nepal': 'NP',
  'नेपाल': 'NP',
  'Bhutan': 'BT',
  'འབྲུག': 'BT',
  'Pakistan': 'PK',
  'پاکستان': 'PK',
  'Afghanistan': 'AF',
  'افغانستان': 'AF',
  'Iran': 'IR',
  'ایران': 'IR',
  'Iraq': 'IQ',
  'العراق': 'IQ',
  'Syria': 'SY',
  'سوريا': 'SY',
  'Jordan': 'JO',
  'الأردن': 'JO',
  'Lebanon': 'LB',
  'لبنان': 'LB',
  'Saudi Arabia': 'SA',
  'السعودية': 'SA',
  'Yemen': 'YE',
  'اليمن': 'YE',
  'Oman': 'OM',
  'عمان': 'OM',
  'United Arab Emirates': 'AE',
  'الإمارات العربية المتحدة': 'AE',
  'Qatar': 'QA',
  'قطر': 'QA',
  'Bahrain': 'BH',
  'البحرين': 'BH',
  'Kuwait': 'KW',
  'الكويت': 'KW',
  'Thailand': 'TH',
  'ประเทศไทย': 'TH',
  'Vietnam': 'VN',
  'Việt Nam': 'VN',
  'Cambodia': 'KH',
  'កម្ពុជា': 'KH',
  'Laos': 'LA',
  'ລາວ': 'LA',
  'Myanmar': 'MM',
  'မြန်မာနိုင်ငံ': 'MM',
  'Burma': 'MM',
  'Malaysia': 'MY',
  'Singapore': 'SG',
  'Indonesia': 'ID',
  'Philippines': 'PH',
  'Brunei': 'BN',
  'East Timor': 'TL',
  'Timor-Leste': 'TL',
  'Papua New Guinea': 'PG',
  'Solomon Islands': 'SB',
  'Vanuatu': 'VU',
  'Fiji': 'FJ',
  'Tonga': 'TO',
  'Samoa': 'WS',
  'Kiribati': 'KI',
  'Micronesia': 'FM',
  'Palau': 'PW',
  'Marshall Islands': 'MH',
  'Nauru': 'NR',
  'Tuvalu': 'TV',
  'Iceland': 'IS',
  'Ísland': 'IS',
  'Greenland': 'GL',
  'Kalaallit Nunaat': 'GL',
  'Faroe Islands': 'FO',
  'Føroyar': 'FO',
  'Åland Islands': 'AX',
  'Aland': 'AX',
  'Monaco': 'MC',
  'Liechtenstein': 'LI',
  'San Marino': 'SM',
  'Vatican City': 'VA',
  'Città del Vaticano': 'VA',
  'Andorra': 'AD',
  'Luxembourg': 'LU',
  'Lëtzebuerg': 'LU',
  'Malta': 'MT',
  'Belarus': 'BY',
  'Беларусь': 'BY',
  'Ukraine': 'UA',
  'Україна': 'UA',
  'Moldova': 'MD',
  'Romania': 'RO',
  'România': 'RO',
  'Bulgaria': 'BG',
  'България': 'BG',
  'Albania': 'AL',
  'Shqipëria': 'AL',
  'North Macedonia': 'MK',
  'Северна Македонија': 'MK',
  'Croatia': 'HR',
  'Hrvatska': 'HR',
  'Slovenia': 'SI',
  'Slovenija': 'SI',
  'Bosnia and Herzegovina': 'BA',
  'Bosna i Hercegovina': 'BA',
  'Serbia': 'RS',
  'Србија': 'RS',
  'Montenegro': 'ME',
  'Црна Гора': 'ME',
  'Kosovo': 'XK',
  'Kosova': 'XK',
  'Estonia': 'EE',
  'Eesti': 'EE',
  'Latvia': 'LV',
  'Latvija': 'LV',
  'Lithuania': 'LT',
  'Lietuva': 'LT',
  'North Korea': 'KP',
  '조선민주주의인민공화국': 'KP',
  'Mongolia': 'MN',
  'Монгол Улс': 'MN',
  'Kazakhstan': 'KZ',
  'Қазақстан': 'KZ',
  'Kyrgyzstan': 'KG',
  'Кыргызстан': 'KG',
  'Tajikistan': 'TJ',
  'Тоҷикистон': 'TJ',
  'Turkmenistan': 'TM',
  'Türkmenistan': 'TM',
  'Uzbekistan': 'UZ',
  'Oʻzbekiston': 'UZ',
  'Azerbaijan': 'AZ',
  'Azərbaycan': 'AZ',
  'Georgia': 'GE',
  'საქართველო': 'GE',
  'Armenia': 'AM',
  'Հայաստան': 'AM',
  'Cyprus': 'CY',
  'Κύπρος': 'CY',
  'Northern Cyprus': 'NC',
  'Kuzey Kıbrıs': 'NC',
};

export function getCountryCode(countryName: string): string {
  if (!countryName) return 'US';

  // Direct match
  if (countryCodeMap[countryName]) return countryCodeMap[countryName];

  // Case-insensitive
  const lower = countryName.toLowerCase();
  for (const [name, code] of Object.entries(countryCodeMap)) {
    if (name.toLowerCase() === lower) return code;
  }

  // Fallback heuristic: take first two letters
  const words = countryName.split(' ');
  const potential = words[0]?.slice(0, 2).toUpperCase();
  if (potential && /^[A-Z]{2}$/.test(potential)) return potential;

  // Default
  return 'US';
}
